#!/bin/bash

# Script criado para apagar arquivos de backup do banco de dados do SGH com mais de 7 dias de armazenamento. 

# Configurações

DIRETORIO="/home/dados/work/spdata/backup/zipdata"

# Excluir backups antigos 
find "${DIRETORIO}" -name "sghdados.gbk-*.zip" -type f -mtime +7 -exec rm {} \;
find "${DIRETORIO}" -name "sghimagens.gbk-*.zip" -type f -mtime +7 -exec rm {} \;
find "${DIRETORIO}" -name "sghlog.gbk-*.zip" -type f -mtime +7 -exec rm {} \;


