#!/bin/bash

# Configurações

DIRETORIO="/home/dados/work/spdata/backup/glpi/db"
CAMINHO="/home/dados/work/spdata/backup/glpi/dir"

# Comandos para apagar arquivos antigos

find "${DIRETORIO}" -name "glpi_db_backup_*.sql.gz" -type f -mtime +7 -exec rm {} \;
find "${CAMINHO}" -name "glpi_dir_backup_*.tar.gz" -type f -mtime +7 -exec rm {} \;

echo "feito"

# SCRIPT FEITO POR DANIEL RICHARD




